version: "3"
checks:
  argument-count:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  class-lines:
    enabled: true
engines:
  rubocop:
    enabled: false
  eslint:
    enabled: false
  duplication:
    enabled: true
  fixme:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
    - "**.py"
exclude_patterns:
  - "tests/*"
